#version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: m1s3.Ql
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_mysql
      MYSQL_PASSWORD: w0.r3Us
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "description=WordPress for tests."
    image: my-wordpress-local:v1
    container_name: wp_app
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_mysql
      WORDPRESS_DB_PASSWORD: w0.r3Us
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config:/var/www/html/wp-config
    user: "1001:1001"
    depends_on:
      - db
    networks:
      - wp_network

volumes:
  db_data:

networks:
  wp_network:
    driver: bridge